### ISSUE TITLE
Question: Is it possible to use repro-sources-list.sh to set a date different from (more up-to-date than) the base image tag?

### ISSUE THREAD

**Issue by codethief** [reproducible-containers/repro-sources-list.sh#13]
As the examples here in the repo suggest, one can/should pin Ubuntu and Debian images using a date tag, e.g.

```
FROM ubuntu:jammy-20230804
# or
FROM debian:bookworm-20230904-slim
```

However, those images only get published occasionally, which causes problems the second a vulnerability gets reported in some package and an update to a package version published *after* the given date `20230904` is needed.

Is it possible to have repo-sources-list.sh set a more recent snapshot date, independently of the Ubuntu/Debian image tag? In other words, the base image would be e.g. `debian:bookworm-20230904-slim` but the repo sources would then get set to, say, the 2024-04-07 snapshot from snapshot.debian.org. Of course, this would trigger lots of upgrades during `apt-get update && apt-get upgrade` later but that is fine / is actually the point.

**Comment by AkihiroSuda** [comment]
Yes, by setting `ARG SOURCE_DATE_EPOCH` to a Unix epoch timestamp.

https://github.com/reproducible-containers/repro-sources-list.sh/tree/v0.1.1?tab=readme-ov-file#environment-variables

**Comment by codethief** [comment]
@AkihiroSuda Thanks so much! I just gave this a try and it works like a charm! :)

**Comment by codethief** [comment]
@AkihiroSuda Thanks so much! I just gave this a try and it works like a charm! :)
